# Basic config
baseURL = "https://blog.they.consulting"
theme = "hugo-simple"
languageCode = "en"                # zh-Hans
title = "Hugo Simple"
copyright = "© 2024 they consulting GmbH"

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

# https://github.com/gohugoio/hugo/issues/12152
capitalizeListTitles = false

# Generate "Bearblog"-like URLs !only!, see https://bearblog.dev/.
disableKinds = ["taxonomy"]
# ignoreErrors = ["error-disable-taxonomy"]
[taxonomies]
tag = "tags"

[permalinks]
blog = "/:slugorfilename/"
tags = "/blog/:slug"

[markup.goldmark.renderer]
unsafe = true
[markup.tableOfContents]
startLevel = 2
endLevel = 3
[markup.highlight]
lineNos = true
lineNumbersInTable = false
noClasses = true
style = "catppuccin-mocha"

[params]
title = "they consulting blog"
description = "Hugo Simple Demo"
favicon = "images/favicon.png"
dateFormat = "2006-01-02"
hideMadeWithLine = true
hideRSSLink = false

[params.author]
name = "they consulting"
email = "info@they-consulting.de"

[[menu.main]]
name = "Home"
pageRef = "/"
weight = 10
[[menu.main]]
name = "Blog"
pageRef = "/blog"
weight = 20

[services.rss]
limit = 42

[pagination]
pagerSize = 16

[outputs]
# Generate RSS for home only.
section = ["html"]
taxonomy = ["html"]
term = ["html"]
